# Generated by Django 3.2.8 on 2021-10-30 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('notes', models.TextField(max_length=360)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=32)),
                ('purchased', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groceryitem')),
            ],
        ),
    ]
