# Generated by Django 3.2.8 on 2021-10-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='notes',
            field=models.TextField(blank=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='unit',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
