# Generated by Django 3.2.8 on 2021-10-30 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211030_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocerylist',
            old_name='items',
            new_name='item',
        ),
    ]
